
[build]

  base = "project/"

  publish = "public/"

  command = "CI=false npm run build"

  functions = "functions/"

[context.production]
  publish = "output/"
  command = "make publish"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "14.15.3" }

[context.deploy-preview]
  publish = "dist/"

[context.deploy-preview.environment]
  ACCESS_TOKEN = "not so secret"

[context.branch-deploy]
  command = "echo branch"
[context.branch-deploy.environment]
  NODE_ENV = "development"

[context.staging] # “staging” is a branch name
  command = "echo 'staging'"
  base = "staging"

[context."feat/branch"]
  command = "echo 'special branch'"
  base = "branch"


[[redirects]]
  from = "/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/old-path"
  to = "/new-path"

  status = 302

  force = true

  query = {id = ":id"}

  conditions = {Language = ["en"], Country = ["US"]}

  signed = "API_SIGNATURE_TOKEN"

  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"

[[redirects]]
  from = "/gated-path"
  status = 200
  conditions = {Role = ["admin"]}
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"

    # Multi-value headers are expressed with multi-line strings.
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''